const VOCABULARY = [
  "activity",
  "amount",
  "author",
  "character",
  "dictionary",
  "event",
  "guess",
  "dashboard",
  "task manager",
  "sick day",
  "trouble",
  "deadline",
  "reason",
  "to-do list",
  "remark",
  "proofreading",
  "performance",
  "co-working space",
  "duty",
  "function",
  "burnout",
  "goal",
  "timetable",
  "area",
  "state",
  "mentoring",
  "tiredness",
  "probation period",
  "expectation",
  "benefit",
  "salary",
  "outsource",
  "team",
  "lead",
  "project",
  "check out",
  "research",
  "routine",
  "planner",
  "schedule",
  "cartoon",
  "movie",
  "circus",
  "composer",
  "dream",
  "daily routine",
  "horror",
  "laughter",
  "novel",
  "story",
  "weather forecast",
  "thought",
  "writer",
  "access",
  "account",
  "adventure",
  "affair",
  "anniversary",
  "entertainment",
  "amusement",
  "influence",
  "attraction",
  "rock-climbing",
  "cycling",
  "number painting",
  "swimming pool",
  "yoga",
  "coffee shop",
  "central park",
  "inspiration",
  "scenery",
  "landscape",
  "computer game",
  "mood",
  "situation",
  "movement",
  "arrangement",
  "accommodation",
  "beverage",
  "binge",
  "activist",
  "pollution",
  "impurity",
  "algae",
  "Earth",
  "atmosphere",
  "environment",
  "climate",
  "air",
  "water reserve",
  "greenhouse effect",
  "oxygen",
  "explorer",
  "investigation",
  "future",
  "tropic forest",
  "humidity",
  "flora",
  "wildlife",
  "plastic waste",
  "А recycling",
  "hydrosphere",
  "meeting",
  "background",
  "bank",
  "banner",
  "beast",
  "cave",
  "caviar",
  "charity",
  "chemistry",
  "economical use",
  "cohesion",
  "commitment",
  "concern",
  "conscience",
  "court",
  "custody",
  "desert",
  "dimension",
  "disaster",
  "disease",
  "downturn",
  "drain",
  "emphasis",
  "engine",
  "evidence",
  "excess",
  "famine",
  "detriment",
];

export default VOCABULARY;